### ISSUE TITLE
numamma hangs when NUMAMMA_ALARM is set

### ISSUE THREAD

**Issue by trahay** [numamma/numamma#3]
In some cases, setting NUMAMMA_ALARM will cause numamma to hang. Here's an example of backtrace that shows the problem: 

```
(gdb) bt
#0  0x00007fffed30e12c in __lll_lock_wait_private () from /lib64/libc.so.6
#1  0x00007fffed28bf93 in _L_lock_14932 () from /lib64/libc.so.6
#2  0x00007fffed289013 in malloc () from /lib64/libc.so.6
#3  0x00007fffed5ceb70 in malloc (size=56) at /lustre/home/y21/trahay/Soft/numamma_install/numamma/src/mem_intercept.c:130
#4  0x00007fffed5d3ad6 in __copy_samples (sm=0x7fffedae9758, access_type=ACCESS_READ) at /lustre/home/y21/trahay/Soft/numamma_install/numamma/src/mem_sampling.c:479
#5  0x00007fffed5d4b2d in __analyze_sampling (sm=0x7fffedae9758, access_type=ACCESS_READ) at /lustre/home/y21/trahay/Soft/numamma_install/numamma/src/mem_sampling.c:678
#6  0x00007fffed5d3907 in mem_sampling_collect_samples () at /lustre/home/y21/trahay/Soft/numamma_install/numamma/src/mem_sampling.c:437
#7  0x00007fffed5d166d in sig_handler (signal=14) at /lustre/home/y21/trahay/Soft/numamma_install/numamma/src/mem_sampling.c:86
#8  <signal handler called>
#9  0x00007fffed286be5 in _int_malloc () from /lib64/libc.so.6
#10 0x00007fffed288fbc in malloc () from /lib64/libc.so.6
#11 0x00007fffed5ceb70 in malloc (size=3200) at /lustre/home/y21/trahay/Soft/numamma_install/numamma/src/mem_intercept.c:130
#12 0x0000000000400aa1 in main (argc=2, argv=0x7fffffffe0b8) at mat_mul.c:78

```

**Comment by trahay** [comment]
There was a race condition in malloc/sighandler. It is now fixed in numamma-1.0.
